kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: nbulai/ruby-chromedriver:latest
  environment:
    RAILS_ENV: test
  commands:
  - bundle install --frozen --jobs 5 --retry 5
  - yarn install --frozen-lockfile
  - chromedriver -v
  - bundle exec rake assets:precompile
  - bundle exec rake
