kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: 'circleci/ruby:2.5.3-node-browsers'
  commands:
  - bundle install
  - yarn install
  - chromedriver -v
  - bundle exec rake assets:precompile
  - bundle exec rake
