inherit_from: .thoughtbot_rubocop.yml

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
