inherit_gem:
  rubocop-coreyja:
    - config/default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'rails/*/'
    - 'config/**/*'
    - 'node_modules/**/*'

RSpec/MultipleExpectations:
  Enabled: false

