version: 2
jobs:
  test:
    working_directory: ~/package-tracker
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: package-tracker-v1-bundler-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle config --local path "vendor/bundle"
      - run: |
          bundle check ||
            bundle install --frozen --jobs 5 --retry 5
      - run: bundle clean

      # Store bundle cache
      - type: cache-save
        key: package-tracker-v1-bundler-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle


      # Restore yarn cache
      - type: cache-restore
        key: package-tracker-v1-yarn-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}

      # Bundle install dependencies
      - run: yarn install --frozen-lockfile

      # Store bundle cache
      - type: cache-save
        key: package-tracker-v1-yarn-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - type: shell
        command: |
          bundle exec rubocop \
            --config .rubocop.yml \
            --format progress \
            --force-exclusion \
            $(bundle exec rubocop --list-target-files | circleci tests split --split-by=filesize)

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Setup DB
          command: bundle exec rake db:create db:schema:load db:migrate --trace

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)


      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:78:af:2e:79:4d:c9:bf:ac:ca:8e:70:c1:e7:28:0a"
      - run: |
          echo 'dokku.coreyja.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBP6nGreJURW3y+sMBMJFcZz1/Ne58qmLWATp/dhqqSiN9fU70ZqupHe4V6aCD7jLyGOY2EXGVAHM3LQbYB50QhQ=' >> ~/.ssh/known_hosts
      - checkout
      - run:
          name: Deploy with git push
          command: |
            git push $GIT_DEPLOY_USERNAME@$GIT_DEPLOY_HOST:package-tracker master
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build .

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: master

