version: 2
jobs:
  test:
    working_directory: ~/package-tracker
    docker:
      - image:circleci/ruby:2.5.3-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.4.12-alpine
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        key: package-tracker-v1-bundler-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle config --local path "vendor/bundle"
      - run: |
          bundle check ||
            bundle install --frozen --jobs 5 --retry 5
      - run: bundle clean

      # Store bundle cache
      - type: cache-save
        key: package-tracker-v1-bundler-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle


      # Restore yarn cache
      - type: cache-restore
        key: package-tracker-v1-yarn-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}

      # Bundle install dependencies
      - run: yarn install --frozen-lockfile

      # Store bundle cache
      - type: cache-save
        key: package-tracker-v1-yarn-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run: bundle exec rake

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "27:70:c5:09:00:c4:03:97:13:2e:f5:47:e4:a2:3f:97"
      - run: |
          echo 'dokku.coreyja.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG2yW0ZfNQWo1fXW1Tca2rTJE9dcN+8uCadvIp0YSsrgFd/6qv14KCR+ClmmIpBqXQV04yjZ3b09P6APJrQm3wg=' >> ~/.ssh/known_hosts
      - checkout
      - run:
          name: Deploy with git push
          command: |
            git push $GIT_DEPLOY_USERNAME@$GIT_DEPLOY_HOST:package-tracker master

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

