# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a725c410670e14caec9b5e16f0a6597c4bcc2b92621d6b2fe7951ddacdb5c64d463e2dcbdeb5e88517875c0a8e29244a39b53c227384e07a8eb66cd9ef4e933
  easypost_api_key: <%= ENV["EASYPOST_TEST_API_KEY"] %>
  slack_url: <%= ENV['SLACK_POST_URL'] %>

test:
  secret_key_base: 45b0d2c5517864d753ad9a90f52680fc7a85eff9a854d5e6e1a86a8377628c820bde32ffc0ff404b85378860b994b2ce3819429ed98fbe9023b725b6e67b7442
  easypost_api_key: TEST_EASYPOST_API_KEY
  slack_url: "https://hooks.slack.com/services/random/other_rando/more_chars"


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  easypost_api_key: <%= ENV["EASYPOST_API_KEY"] %>
  slack_url: <%= ENV['SLACK_POST_URL'] %>
